# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-23 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordinarymember',
            old_name='birthday',
            new_name='昵称',
        ),
        migrations.RenameField(
            model_name='ordinarymember',
            old_name='nickname',
            new_name='生日',
        ),
    ]
